version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kelaskita
    container_name: kelaskita-app
    restart: always
    command: "php artisan serve --host=0.0.0.0 "
    networks:
      - kelaskita
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./public:/var/www/public
      - ./storage:/var/www/storage
      - ./.env:/var/www/.env

  db:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      # After database deployed in dev environment, re-setup
      # root password for KelasKita application.
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: kelaskita
    networks:
      - kelaskita
    volumes:
      - kelaskita-db-data:/var/lib/mysql


# Keep mysql database and configuration persistent
# Stored in /var/lib/docker/volumes/<volume-name>
volumes:
  kelaskita-db-data:
  
networks:
  kelaskita:
    driver: bridge
